import * as T from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {data,makeModel,makeTrain} from './models.js';
const $=s=>document.querySelector(s), viewport=$('#viewport');
let current='cbs-0046',model,renderer,scene,camera,controls,train,view='overview';
let paused=matchMedia('(prefers-reduced-motion: reduce)').matches, elapsed=0,last=performance.now(),lastUi=-1;
const PERIOD=30,CROSSING=14;
function syncPause(){$('#pause').textContent=paused?'Resume':'Pause';$('#pause').setAttribute('aria-pressed',String(paused));}
function info(){const d=data[current];$('#project-title').textContent=d.title;$('#project-description').textContent=d.description;$('#scene-id').textContent=current.toUpperCase();$('#dimension-list').replaceChildren(...d.rows.map(([name,value])=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value;row.append(dt,dd);return row;}));$('#source-note').textContent=d.note;for(const id of ['pdf-link','pdf-download'])$('#'+id).href=`assets/${current}.pdf`;$('#pdf-download').download=`${current.toUpperCase()}.pdf`;$('#board-image').src=`assets/${current}.jpg`;$('#board-image').alt=`${current.toUpperCase()} installed view, detail and section`;document.querySelectorAll('[data-project]').forEach(b=>{const sel=b.dataset.project===current;b.classList.toggle('selected',sel);b.setAttribute('aria-pressed',String(sel));});}
function pose(which='overview'){view=which;if(!camera)return;model.removable.visible=which!=='section';renderer.clippingPlanes=which==='section'?[new T.Plane(new T.Vector3(-1,0,0),0)]:[];if(which==='overview'){camera.position.set(29,22,33);controls.target.set(0,current==='cbs-0045'?5:3,0);}else if(which==='close'){camera.position.set(current==='b-221-2024'?-5:9,model.pathY+3,10);controls.target.set(current==='b-221-2024'?-1.5:0,model.pathY,3);}else if(which==='section'){camera.position.set(current==='cbs-0045'?17:21,model.pathY+3,.15);controls.target.set(0,model.pathY-1,0);}else{camera.position.set(.01,40,.01);controls.target.set(0,3,0);}controls.update();document.querySelectorAll('[data-view]').forEach(b=>{const yes=b.dataset.view===which;b.classList.toggle('active',yes);b.setAttribute('aria-pressed',String(yes));});}
function disposeGroup(group){group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.isSprite){o.material.map?.dispose();o.material.dispose();}});}
function select(id){current=id;info();if(scene){if(model){scene.remove(model.group);disposeGroup(model.group);}model=makeModel(id);scene.add(model.group);model.dims.visible=$('#dimensions').checked;model.ohe.visible=$('#overhead').checked;train.position.y=model.railY+.07;pose('overview');}}
function resize(){if(!renderer)return;const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
function animate(now){const dt=Math.min((now-last)/1000,.1);last=now;if(!paused&&!document.hidden)elapsed+=dt;const t=elapsed%PERIOD;train.visible=t<CROSSING;const travel=model.len+8*23.8+24;train.position.x=-model.len/2-16+t/CROSSING*travel;controls.update();renderer.render(scene,camera);const tick=Math.floor(elapsed*4);if(tick!==lastUi||paused){$('#train-status').textContent=paused?'Animation paused':t<CROSSING?'Crossing · repeats every 30 seconds':`Next pass in ${Math.ceil(PERIOD-t)} seconds`;$('#progress').style.width=`${t/PERIOD*100}%`;lastUi=tick;}requestAnimationFrame(animate);}
info();
try{
 renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor('#e9f0f4');renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;viewport.prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive railway bridge model. Use the view buttons or drag to rotate.');renderer.domElement.setAttribute('role','img');
 scene=new T.Scene();scene.fog=new T.Fog('#e9f0f4',90,220);scene.add(new T.HemisphereLight('#ecf5ff','#9a9f94',2.3));const sun=new T.DirectionalLight('#fff7e8',3.5);sun.position.set(-16,35,22);scene.add(sun);scene.add(new T.AmbientLight('#ffffff',.3));
 camera=new T.PerspectiveCamera(40,1,.1,500);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=2;controls.maxDistance=85;controls.maxPolarAngle=Math.PI*.49;controls.target.set(0,3,0);controls.enablePan=true;
 const floor=new T.Mesh(new T.PlaneGeometry(250,160),new T.MeshStandardMaterial({color:'#dce5e7',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.8;scene.add(floor);const grid=new T.GridHelper(90,45,'#c9d6dc','#d5dfe3');grid.position.y=-2.78;scene.add(grid);
 train=makeTrain();scene.add(train);select(current);resize();new ResizeObserver(resize).observe(viewport);$('#loading').hidden=true;syncPause();requestAnimationFrame(animate);
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('#fallback').hidden=false;$('#fallback').querySelector('h2').textContent='The 3D view was interrupted.';$('#fallback').querySelector('p').textContent='Reload the page to restore 3D, or use the visualisation and PDF below.';});
}catch(error){console.error('3D scene unavailable:',error);$('#loading').hidden=true;$('#fallback').hidden=false;info();$('#train-status').textContent='3D animation unavailable';for(const el of [$('#pause'),$('#run-train'),$('#dimensions'),$('#overhead'),$('#zoom-in'),$('#zoom-out'),$('#reset')])el.disabled=true;}
document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.project)));
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>pose(b.dataset.view)));
$('#dimensions').addEventListener('change',e=>{if(model)model.dims.visible=e.target.checked;});$('#overhead').addEventListener('change',e=>{if(model)model.ohe.visible=e.target.checked;});
$('#pause').addEventListener('click',()=>{paused=!paused;lastUi=-1;syncPause();});$('#run-train').addEventListener('click',()=>{elapsed=0;paused=false;lastUi=-1;syncPause();});$('#reset').addEventListener('click',()=>pose('overview'));
for(const [id,m] of [['zoom-in',.78],['zoom-out',1.28]])$('#'+id).addEventListener('click',()=>{if(!camera)return;const offset=camera.position.clone().sub(controls.target);offset.multiplyScalar(m).clampLength(controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).add(offset);controls.update();});
$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('.viewer-card').requestFullscreen)await $('.viewer-card').requestFullscreen();else{viewport.scrollIntoView({block:'start'});}}catch{viewport.scrollIntoView({block:'start'});}});
const dialog=$('#image-dialog');let zoom=100;function showBoard(){$('#large-image').src=`assets/${current}.jpg`;$('#large-image').alt=`${current.toUpperCase()} visualisation board`;$('#dialog-title').textContent=current.toUpperCase()+' · Visualisation';zoom=100;$('#large-image').style.width='100%';dialog.showModal();}$('#board-button').addEventListener('click',showBoard);$('#expand-board').addEventListener('click',showBoard);$('#close-dialog').addEventListener('click',()=>dialog.close());for(const [id,v] of [['image-plus',50],['image-minus',-50]])$('#'+id).addEventListener('click',()=>{zoom=Math.max(100,Math.min(400,zoom+v));$('#large-image').style.width=zoom+'%';});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
document.addEventListener('visibilitychange',()=>{last=performance.now();});
